[启动参数]
teams路径 = C:/Program Files (x86)/Steam/steam.exe
任务选项 = 签到,邮件,任务,扭蛋,挑战赛-活动
;"挑战赛-活动":
;"挑战赛-自定义": 挑战赛无线打设定的窗口
;"扭蛋":自动抽奖，参考扭蛋配置,最好配置再最后防止重复
;"签到"
;"邮件"：领取邮件奖励
;"任务"：领取任务奖励
[扭蛋]
抽奖窗口 = 10
模式总数 = 2
模式选项 = 2
抽奖次数 = 1

[挑战赛-自定义]
挑战窗口 = 4
;自定义无线挑战推荐窗口
[全局参数]
自动体力 = 否
;检测到有吃水界面自动吃水

